server:
  port: 8888
spring:
  profiles:
    active:
      - insecure
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file:///Users/denglt/onGithub/localconfig
          #uri: https://github.com/denglt/springcloud
          searchPaths: config-repo
          username:
          password:
          hostKeyAlgorithm:
          host-key:
          private-key:
        overrides:
          foo: bar
        health:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

---
spring:
  profiles: insecure
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
---
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: configserver
      roles: ADMIN