# Server HTTP port.
server:
  servlet:
    context-path: /demoserver
    session:
      timeout:
  port: 8881
  address:
  connection-timeout: 10s

spring:
  security:
    user:
      name: admin
      password: demoserver
  data:
    elasticsearch:
      cluster-nodes: 47.106.93.69:9300
      # properties: { es.set.netty.runtime.available.processors: false }
  task:
    execution:
      pool:
        core-pool-size: 1
        max-pool-size: 10
        queue-capacity: 100
        keep-alive-seconds: 60
    scheduler:
      pool:
        pool-size: 5
        thread-name-prefix: my-scheduled-pool

# Actuator 监控
management:
  server:
    servlet:
      context-path: /demoserver
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

#/info Endpoint
info:
  app:
    name: Demo Server
    description: prod
    version: 2.0.0

eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: ${management.server.servlet.context-path}/info
    #health-check-url-path: ${management.server.servlet.context-path}/health
    metadata-map:
      name: demoserver
      version: 1.0
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: true
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: true
    service-url:
      #defaultZone: http://admin:eurekaserver@127.0.0.1:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
