# Server HTTP port.
server:
  servlet:
    context-path: /demoserver
    session:
      timeout:
  port: 8881
  address:
  connection-timeout: 10s


# Actuator 监控
management:
  server:
    servlet:
      context-path: /demoserver
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

#/info Endpoint
info:
  app:
    name: Demo Server
    description: prod
    version: 3.0.0

eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: ${management.server.servlet.context-path}/info
    #health-check-url-path: ${management.server.servlet.context-path}/health
    #home-page-url-path:
    #发送心跳时间间隔
    lease-renewal-interval-in-seconds: 5
    #服务端多久没有收到心跳，将删除实例
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      name: demoserver
      version: 1.0
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: true
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      #defaultZone: http://admin:eurekaserver@127.0.0.1:8761/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761}/eureka/
    enabled: true
    healthcheck:
      enabled: true


---
spring:
  profiles: insecure
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
---
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: demoserver

---
spring:
  profiles: eureka-secure

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:eurekaserver@127.0.0.1:8761}/eureka/

---
spring:
  profiles: eureka-insecure
