# 负载均衡自动配置  LoadBalancerAutoConfiguration

#远程服务配置重试配置： RibbonAutoConfiguration  RibbonClientConfiguration
userserver:  # 服务名称
  ribbon:
    retryableStatusCodes: 404,502,500   #错误重试状态码 RibbonLoadBalancedRetryFactory ，RibbonLoadBalancedRetryPolicy(该类默认只对GET方法进行retry)

ribbon:  # 默认配置(所有服务)
  retryableStatusCodes: 404,502,500
  PoolMaxThreads: 200 # default 200
  PoolMinThreads: 1   # default 1
  ConnectTimeout: 2000 # default 2000
  ReadTimeout: 3000    # default 5000
  MaxTotalConnections: 500  # default 200
  MaxConnectionsPerHost: 100 # default 50
  OkToRetryOnAllOperations: true # default false RibbonLoadBalancedRetryPolicy(该类默认只对GET方法进行retry)
  MaxAutoRetriesNextServer: 1 # default 1

feign:
  hystrix.enabled: true  # default false

# Server HTTP port.
server:
  servlet:
    context-path: /demoserver
    session:
      timeout:
  port: 8881
  address:
  connection-timeout: 10s


# Actuator 监控
management:
  server:
    servlet:
      context-path: /demoserver
  endpoints:
    web:
      exposure:
        include: "*"
        #  - hystrix.stream
  endpoint:
    health:
      enabled: true
      show-details: always

#/info Endpoint
info:
  app:
    name: Demo Server
    description: prod
    version: 3.0.0

eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: ${management.server.servlet.context-path}/info
    #health-check-url-path: ${management.server.servlet.context-path}/health
    #home-page-url-path:
    #发送心跳时间间隔
    lease-renewal-interval-in-seconds: 5
    #服务端多久没有收到心跳，将删除实例
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      name: demoserver
      version: 1.0
  client:
    register-with-eureka: true  #是否向eureka server注册service
    fetch-registry: true   # 是否从eureka server获取service
    registry-fetch-interval-seconds: 5
    service-url:
      #defaultZone: http://admin:eurekaserver@127.0.0.1:8761/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761}/eureka/
    enabled: true
    healthcheck:
      enabled: true

spring:
  cloud:
    inetutils:
      useOnlySiteLocalInterfaces: true
    loadbalancer:
      # LoadBalancerRetryProperties
      retry.enabled: true   # default true  这个生效的条件,依赖：spring retry（ RetryTemplate）LoadBalancerAutoConfiguration

---
spring:
  profiles: insecure
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
---
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: demoserver

---
spring:
  profiles: eureka-secure

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:eurekaserver@127.0.0.1:8761}/eureka/

---
spring:
  profiles: eureka-insecure
