spring:
  application:
    name: eurekaserver
  profiles:
    active:
      #- insecure
      - secure
server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761}/eureka/
    enabled: true
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

---
spring:
  profiles: insecure
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

---
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: eurekaserver
      roles: ADMIN
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:eurekaserver@127.0.0.1:8761}/eureka/
      Authorization: Basic YWRtaW46ZXVyZWthc2VydmVy