# Server HTTP port.
server:
  servlet:
    context-path: /userserver
    session:
      timeout:
  port: 8882
  address:
  connection-timeout: 10s

spring:
  profiles:
    active:
    # - insecure
    - secure
    - eureka-secure
  cloud:
    stream:  # BindingServiceProperties
      bindings:  # BindingProperties
        input:
          binder: kafka1
          contentType: application/json
          destination: userTopic
          group:  denglt-userservice-1
          #group: denglt.01d6464d-86c3-4d41-b496-92e1adbd70dd #anonymous.869011ac-ee01-4d71-bdaa-9aca0f9b2a9f
          consumer: # ConsumerProperties
            maxAttempts: 1  # default 3
            concurrency: 1  # default 1  (可以设置为partition数量)
        output:
          binder: kafka2
          contentType: application/json
          destination: userTopic
      binders: # BinderProperties
        kafka1:
          type: kafka # kafka: org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfiguration

        kafka2:
          type: kafka


# Actuator 监控
management:
  server:
    servlet:
      context-path: /userserver
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

#/info Endpoint
info:
  app:
    name: User Server
    description: prod
    version: 3.0.0

eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: ${management.server.servlet.context-path}/info
    #health-check-url-path: ${management.server.servlet.context-path}/health

    #发送心跳时间间隔
    lease-renewal-interval-in-seconds: 5
    #服务端多久没有收到心跳，将删除实例
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      name: userserver
      version: 1.0
  client:
    register-with-eureka: true  #是否向eureka server注册service
    fetch-registry: true   # 是否从eureka server获取service
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761}/eureka/
    enabled: true
    healthcheck:
      enabled: true

---
spring:
  profiles: insecure
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
---
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: userserver

---
spring:
  profiles: eureka-secure

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:eurekaserver@127.0.0.1:8761}/eureka/
---
spring:
  profiles: eureka-insecure

---
spring:
  profiles: prod2
server:
  port: 8883