# Server HTTP port.
server:
  servlet:
    context-path: /userserver
    session:
      timeout:
  port: 8882
  address:
  connection-timeout: 10s

spring:
  security:
    user:
      name: admin
      password: userserver


# Actuator 监控
management:
  server:
    servlet:
      context-path: /userserver
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

#/info Endpoint
info:
  app:
    name: User Server
    description: prod
    version: 3.0.0

eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: ${management.server.servlet.context-path}/info
    #health-check-url-path: ${management.server.servlet.context-path}/health
    metadata-map:
      name: userserver
      version: 1.0
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: true
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: true
    service-url:
      #defaultZone: http://admin:eurekaserver@127.0.0.1:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
