
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/denglt/springcloud
          #uri: file:///Users/denglt/onGithub/spring-cloud-config-repo
          searchPaths: config-repo
         # username:
         # password:
          hostKeyAlgorithm:
          host-key:
          private-key:
        overrides:
          foo: bar
        health:
          #repositories:
            #application:
            #  lable: mylabel
          enabled: true




